schema_version: 1.2.0
id: CVE-2021-43798
aliases:
- GHSA-8pjx-jj86-j47p
modified: 2021-12-29T21:15Z
published: 2021-12-07T19:15Z
details: 'Grafana is an open-source platform for monitoring and observability. Grafana
  versions 8.0.0-beta1 through 8.3.0 (except for patched versions) iss vulnerable
  to directory traversal, allowing access to local files. The vulnerable URL path
  is: `<grafana_host_url>/public/plugins//`, where is the plugin ID for any installed
  plugin. At no time has Grafana Cloud been vulnerable. Users are advised to upgrade
  to patched versions 8.0.7, 8.1.8, 8.2.7, or 8.3.1. The GitHub Security Advisory
  contains more information about vulnerable URL paths, mitigation, and the disclosure
  timeline.'
severity:
- type: CVSS_V3
  score: 7.5
- type: CVSS_V2
  score: 5.0
affected:
- package:
    name: grafana
    cpe: cpe:2.3:a:grafana:grafana
- ranges:
  - type: GIT
    repo: https://github.com/grafana/grafana
    events:
    - introduced: '0'
    - fixed: c798c0e958d15d9cc7f27c72113d572fa58545ce
- versions:
  - 8.3.0
  - 8.0.0
- database_specific:
    CWE:
    - CWE-22
    CVSS:
      Score: 7.5
      Severity: HIGH
      Code: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
references:
- type: WEB
  url: http://www.openwall.com/lists/oss-security/2021/12/09/2
- type: WEB
  url: http://packetstormsecurity.com/files/165221/Grafana-8.3.0-Directory-Traversal-Arbitrary-File-Read.html
- type: WEB
  url: https://grafana.com/blog/2021/12/08/an-update-on-0day-cve-2021-43798-grafana-directory-traversal/
- type: FIX
  url: https://github.com/grafana/grafana/commit/c798c0e958d15d9cc7f27c72113d572fa58545ce
- type: ADVISORY
  url: https://security.netapp.com/advisory/ntap-20211229-0004/
- type: WEB
  url: http://www.openwall.com/lists/oss-security/2021/12/10/4
- type: ADVISORY
  url: https://github.com/grafana/grafana/security/advisories/GHSA-8pjx-jj86-j47p
- type: WEB
  url: http://packetstormsecurity.com/files/165198/Grafana-Arbitrary-File-Reading.html
