schema_version: 1.2.0
id: CVE-2020-15129
aliases:
- GHSA-6qq8-5wq3-86rp
modified: 2021-07-28T15:03Z
published: 2020-07-30T16:15Z
details: In Traefik before versions 1.7.26, 2.2.8, and 2.3.0-rc3, there exists a potential
  open redirect vulnerability in Traefik's handling of the "X-Forwarded-Prefix" header.
  The Traefik API dashboard component doesn't validate that the value of the header
  "X-Forwarded-Prefix" is a site relative path and will redirect to any header provided
  URI. Successful exploitation of an open redirect can be used to entice victims to
  disclose sensitive information. Active Exploitation of this issue is unlikely as
  it would require active header injection, however the Traefik team addressed this
  issue nonetheless to prevent abuse in e.g. cache poisoning scenarios.
severity:
- type: CVSS_V3
  score: 4.7
- type: CVSS_V2
  score: 4.0
affected:
- package:
    name: traefik
    cpe: cpe:2.3:a:traefik:traefik
- ranges:
  - type: GIT
    repo: https://github.com/containous/traefik
    events:
    - introduced: '0'
    - fixed: e63db782c11c7b8bfce30be4c902e7ef8f9f33d2
- versions:
  - 2.3.0
- database_specific:
    CWE:
    - CWE-601
    CVSS:
      Score: 4.7
      Severity: MEDIUM
      Code: CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:L/I:L/A:N
references:
- type: FIX
  url: https://github.com/containous/traefik/commit/e63db782c11c7b8bfce30be4c902e7ef8f9f33d2
- type: ADVISORY
  url: https://github.com/containous/traefik/security/advisories/GHSA-6qq8-5wq3-86rp
- type: WEB
  url: https://github.com/containous/traefik/releases/tag/v1.7.26
- type: WEB
  url: https://github.com/containous/traefik/pull/7109
- type: WEB
  url: https://github.com/containous/traefik/releases/tag/v2.2.8
- type: WEB
  url: https://github.com/containous/traefik/releases/tag/v2.3.0-rc3
