schema_version: 1.2.0
id: CVE-2020-15186
aliases:
- GHSA-m54r-vrmv-hw33
modified: 2021-11-18T17:50Z
published: 2020-09-17T22:15Z
details: In Helm before versions 2.16.11 and 3.3.2 plugin names are not sanitized
  properly. As a result, a malicious plugin author could use characters in a plugin
  name that would result in unexpected behavior, such as duplicating the name of another
  plugin or spoofing the output to `helm --help`. This issue has been patched in Helm
  3.3.2. A possible workaround is to not install untrusted Helm plugins. Examine the
  `name` field in the `plugin.yaml` file for a plugin, looking for characters outside
  of the [a-zA-Z0-9._-] range.
severity:
- type: CVSS_V3
  score: 2.7
- type: CVSS_V2
  score: 4.0
affected:
- package:
    name: helm
    cpe: cpe:2.3:a:helm:helm
- ranges:
  - type: GIT
    repo: https://github.com/helm/helm
    events:
    - introduced: '0'
    - fixed: 809e2d999e2c33e20e77f6bff30652d79c287542
- database_specific:
    CWE:
    - CWE-74
    CVSS:
      Score: 2.7
      Severity: LOW
      Code: CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:N/I:L/A:N
references:
- type: FIX
  url: https://github.com/helm/helm/commit/809e2d999e2c33e20e77f6bff30652d79c287542
- type: ADVISORY
  url: https://github.com/helm/helm/security/advisories/GHSA-m54r-vrmv-hw33
