schema_version: 1.2.0
id: CVE-2020-4053
aliases:
- GHSA-qq3j-xp49-j73f
modified: 2020-07-06T16:47Z
published: 2020-06-16T22:15Z
details: In Helm greater than or equal to 3.0.0 and less than 3.2.4, a path traversal
  attack is possible when installing Helm plugins from a tar archive over HTTP. It
  is possible for a malicious plugin author to inject a relative path into a plugin
  archive, and copy a file outside of the intended directory. This has been fixed
  in 3.2.4.
severity:
- type: CVSS_V3
  score: 6.8
- type: CVSS_V2
  score: 8.5
affected:
- package:
    name: helm
    cpe: cpe:2.3:a:helm:helm
- ranges:
  - type: GIT
    repo: https://github.com/helm/helm
    events:
    - introduced: '0'
    - fixed: 0ad800ef43d3b826f31a5ad8dfbb4fe05d143688
- database_specific:
    CWE:
    - CWE-22
    CVSS:
      Score: 6.8
      Severity: MEDIUM
      Code: CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:U/C:H/I:H/A:H
references:
- type: FIX
  url: https://github.com/helm/helm/commit/0ad800ef43d3b826f31a5ad8dfbb4fe05d143688
- type: WEB
  url: https://github.com/helm/helm/releases/tag/v3.2.4
- type: ADVISORY
  url: https://github.com/helm/helm/security/advisories/GHSA-qq3j-xp49-j73f
