schema_version: 1.2.0
id: CVE-2019-3826
aliases: []
modified: 2021-03-31T21:15Z
published: 2019-03-26T18:29Z
details: A stored, DOM based, cross-site scripting (XSS) flaw was found in Prometheus
  before version 2.7.1. An attacker could exploit this by convincing an authenticated
  user to visit a crafted URL on a Prometheus server, allowing for the execution and
  persistent storage of arbitrary scripts.
severity:
- type: CVSS_V3
  score: 6.1
- type: CVSS_V2
  score: 4.3
affected:
- package:
    name: prometheus
    cpe: cpe:2.3:a:prometheus:prometheus
- ranges:
  - type: GIT
    repo: https://github.com/prometheus/prometheus
    events:
    - introduced: '0'
    - fixed: 62e591f9
- database_specific:
    CWE:
    - CWE-79
    CVSS:
      Score: 6.1
      Severity: MEDIUM
      Code: CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
references:
- type: WEB
  url: https://lists.apache.org/thread.html/rdf2a0d94c3b5b523aeff7741ae71347415276062811b687f30ea6573@%3Ccommits.zookeeper.apache.org%3E
- type: WEB
  url: https://access.redhat.com/errata/RHBA-2019:0327
- type: ADVISORY
  url: https://advisory.checkmarx.net/advisory/CX-2019-4297
- type: WEB
  url: https://github.com/prometheus/prometheus/pull/5163
- type: REPORT
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-3826
- type: WEB
  url: https://lists.apache.org/thread.html/r8e3f7da12bf5750b0a02e69a78a61073a2ac950eed7451ce70a65177@%3Ccommits.zookeeper.apache.org%3E
- type: FIX
  url: https://github.com/prometheus/prometheus/commit/62e591f9
- type: WEB
  url: https://lists.apache.org/thread.html/r48d5019bd42e0770f7e5351e420a63a41ff1f16924942442c6aff6a8@%3Ccommits.zookeeper.apache.org%3E
