schema_version: 1.2.0
id: CVE-2020-26222
aliases:
- GHSA-23f7-99jx-m54r
modified: 2020-12-03T15:53Z
published: 2020-11-13T16:15Z
details: 'Dependabot is a set of packages for automated dependency management for
  Ruby, JavaScript, Python, PHP, Elixir, Rust, Java, .NET, Elm and Go. In Dependabot-Core
  from version 0.119.0.beta1 before version 0.125.1, there is a remote code execution
  vulnerability in dependabot-common and dependabot-go_modules when a source branch
  name contains malicious injectable bash code. For example, if Dependabot is configured
  to use the following source branch name: "/$({curl,127.0.0.1})", Dependabot will
  make a HTTP request to the following URL: 127.0.0.1 when cloning the source repository.
  The fix was applied to version 0.125.1. As a workaround, one can escape the branch
  name prior to passing it to the Dependabot::Source class.'
severity:
- type: CVSS_V3
  score: 8.8
- type: CVSS_V2
  score: 6.5
affected:
- package:
    name: dependabot
    cpe: cpe:2.3:a:dependabot_project:dependabot
- ranges:
  - type: GIT
    repo: https://github.com/dependabot/dependabot-core
    events:
    - introduced: '0'
    - fixed: e089116abbe284425b976f7920e502b8e83a61b5
- versions:
  - 0.119.0
- database_specific:
    CWE:
    - CWE-74
    CVSS:
      Score: 8.8
      Severity: HIGH
      Code: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
references:
- type: FIX
  url: https://github.com/dependabot/dependabot-core/commit/e089116abbe284425b976f7920e502b8e83a61b5
- type: ADVISORY
  url: https://github.com/dependabot/dependabot-core/security/advisories/GHSA-23f7-99jx-m54r
- type: WEB
  url: https://github.com/dependabot/dependabot-core/pull/2727
