schema_version: 1.2.0
id: CVE-2014-4967
aliases: []
modified: 2020-02-26T15:35Z
published: 2020-02-18T15:15Z
details: Multiple argument injection vulnerabilities in Ansible before 1.6.7 allow
  remote attackers to execute arbitrary code by leveraging access to an Ansible managed
  host and providing a crafted fact, as demonstrated by a fact with (1) a trailing
  " src=" clause, (2) a trailing " temp=" clause, or (3) a trailing " validate=" clause
  accompanied by a shell command.
severity:
- type: CVSS_V3
  score: 9.8
- type: CVSS_V2
  score: 7.5
affected:
- package:
    name: ansible
    cpe: cpe:2.3:a:redhat:ansible
- ranges:
  - type: GIT
    repo: https://github.com/ansible/ansible
    events:
    - introduced: '0'
    - fixed: 62a1295a3e08cb6c3e9f1b2a1e6e5dcaeab32527
- database_specific:
    CWE:
    - CWE-74
    CVSS:
      Score: 9.8
      Severity: CRITICAL
      Code: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
references:
- type: ADVISORY
  url: http://www.ocert.org/advisories/ocert-2014-004.html
- type: FIX
  url: https://github.com/ansible/ansible/commit/62a1295a3e08cb6c3e9f1b2a1e6e5dcaeab32527
