schema_version: 1.2.0
id: CVE-2014-4966
aliases: []
modified: 2020-02-26T14:40Z
published: 2020-02-18T15:15Z
details: Ansible before 1.6.7 does not prevent inventory data with "{{" and "lookup"
  substrings, and does not prevent remote data with "{{" substrings, which allows
  remote attackers to execute arbitrary code via (1) crafted lookup('pipe') calls
  or (2) crafted Jinja2 data.
severity:
- type: CVSS_V3
  score: 9.8
- type: CVSS_V2
  score: 7.5
affected:
- package:
    name: ansible
    cpe: cpe:2.3:a:redhat:ansible
- ranges:
  - type: GIT
    repo: https://github.com/ansible/ansible
    events:
    - introduced: '0'
    - fixed: 62a1295a3e08cb6c3e9f1b2a1e6e5dcaeab32527
- database_specific:
    CWE:
    - CWE-74
    CVSS:
      Score: 9.8
      Severity: CRITICAL
      Code: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
references:
- type: ADVISORY
  url: http://www.ocert.org/advisories/ocert-2014-004.html
- type: FIX
  url: https://github.com/ansible/ansible/commit/62a1295a3e08cb6c3e9f1b2a1e6e5dcaeab32527
