schema_version: 1.2.0
id: CVE-2014-4660
aliases: []
modified: 2020-02-25T20:13Z
published: 2020-02-20T03:15Z
details: Ansible before 1.5.5 constructs filenames containing user and password fields
  on the basis of deb lines in sources.list, which might allow local users to obtain
  sensitive credential information in opportunistic circumstances by leveraging existence
  of a file that uses the "deb http://user:pass@server:port/" format.
severity:
- type: CVSS_V3
  score: 5.5
- type: CVSS_V2
  score: 2.1
affected:
- package:
    name: ansible
    cpe: cpe:2.3:a:redhat:ansible
- ranges:
  - type: GIT
    repo: https://github.com/ansible/ansible
    events:
    - introduced: '0'
    - fixed: c4b5e46054c74176b2446c82d4df1a2610eddc08
- database_specific:
    CWE:
    - CWE-522
    CVSS:
      Score: 5.5
      Severity: MEDIUM
      Code: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N
references:
- type: WEB
  url: https://github.com/ansible/ansible/blob/release1.5.5/CHANGELOG.md
- type: WEB
  url: https://security-tracker.debian.org/tracker/CVE-2014-4660
- type: WEB
  url: https://www.securityfocus.com/bid/68231
- type: FIX
  url: https://github.com/ansible/ansible/commit/c4b5e46054c74176b2446c82d4df1a2610eddc08
- type: WEB
  url: https://www.openwall.com/lists/oss-security/2014/06/26/19
