schema_version: 1.2.0
id: CVE-2014-3498
aliases: []
modified: 2018-10-30T16:28Z
published: 2017-06-08T18:29Z
details: The user module in ansible before 1.6.6 allows remote authenticated users
  to execute arbitrary commands.
severity:
- type: CVSS_V3
  score: 8.8
- type: CVSS_V2
  score: 6.5
affected:
- package:
    name: ansible
    cpe: cpe:2.3:a:redhat:ansible
- ranges:
  - type: GIT
    repo: https://github.com/ansible/ansible
    events:
    - introduced: '0'
    - fixed: 8ed6350e65c82292a631f08845dfaacffe7f07f5
- database_specific:
    CWE:
    - CWE-20
    CVSS:
      Score: 8.8
      Severity: HIGH
      Code: CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
references:
- type: FIX
  url: https://github.com/ansible/ansible/commit/8ed6350e65c82292a631f08845dfaacffe7f07f5
- type: REPORT
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1335551
