schema_version: 1.2.0
id: CVE-2016-3697
aliases: []
modified: 2021-01-05T17:38Z
published: 2016-06-01T20:59Z
details: libcontainer/user/user.go in runC before 0.1.0, as used in Docker before
  1.11.2, improperly treats a numeric UID as a potential username, which allows local
  users to gain privileges via a numeric username in the password file in a container.
severity:
- type: CVSS_V3
  score: 7.8
- type: CVSS_V2
  score: 2.1
affected:
- package:
    name: docker
    cpe: cpe:2.3:a:docker:docker
- ranges:
  - type: GIT
    repo: https://github.com/opencontainers/runc
    events:
    - introduced: '0'
    - fixed: 69af385de62ea68e2e608335cffbb0f4aa3db091
- database_specific:
    CWE:
    - CWE-264
    CVSS:
      Score: 7.8
      Severity: HIGH
      Code: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
references:
- type: WEB
  url: https://github.com/opencontainers/runc/releases/tag/v0.1.0
- type: WEB
  url: http://rhn.redhat.com/errata/RHSA-2016-2634.html
- type: WEB
  url: https://security.gentoo.org/glsa/201612-28
- type: WEB
  url: https://github.com/opencontainers/runc/pull/708
- type: FIX
  url: https://github.com/opencontainers/runc/commit/69af385de62ea68e2e608335cffbb0f4aa3db091
- type: WEB
  url: http://rhn.redhat.com/errata/RHSA-2016-1034.html
- type: REPORT
  url: https://github.com/docker/docker/issues/21436
- type: WEB
  url: http://lists.opensuse.org/opensuse-updates/2016-05/msg00111.html
